### ISSUE TITLE
Make it clearer that ['apache']['version'] should be a string

### ISSUE THREAD

**Issue by gravitystorm** [viverae-cookbooks/apache2#309]
The readme says "Specifing 2.4 triggers apache 2.4 support" but it doesn't make it clear that it should be a string `'2.4'`, not a plain `2.4` (i.e. a float). 

By mistake I put `default['apache']['version'] = 2.4` in a recipe and it took a while to figure out what was going wrong! The recipe mostly works but important parts are behind string equality checks.

**Comment by drpebcak** [comment]
I added a little something to the readme that should help clear this up.

**Comment by gravitystorm** [comment]
@drpebcak Thanks!
